# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_occupancies_cpp <- function(p_list, transient_states, all_states, init_probs, n, delim = "->") {
    .Call(`_mscalc_calc_occupancy_cpp`, p_list, transient_states, all_states, init_probs, n, delim)
}

